---
title: "Helpful codes"
author: "Ruoyu Wang"
date: "2020/2/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tmap)
library(tmaptools)
library(raster)

```

##### I. Useful website links:

1. Geocomputation with R - chapter 8: Making maps with R

https://geocompr.robinlovelace.net/spatial-class.html

2. tm_layout function (not explore yet)

https://www.rdocumentation.org/packages/tmap/versions/2.3-2/topics/tm_layout

3. tmap: get started!

https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html

4. tmap : the easy way to plot thematic maps and show them interactively in R

https://tlorusso.github.io/geodata_workshop/tmap_package



#### II. Combine multiple polygon layers in one interactive map

```{r}
data(World)
tmap_mode("view")

tm_shape(World) +
	tm_polygons("HPI") +
	tm_facets(by = "continent", as.layers = TRUE)


tm_shape(World) +
	tm_polygons(c("well_being", "life_exp"),
				style=c("pretty", "fixed"), breaks=list(NULL, c(65,70,75,80,85)),
				palette=list("Oranges", "Purples"),
				border.col = "black",
				legend.show = c(FALSE,TRUE),
				title=c("Well-Being Index", "Life Expectancy")) +
	tm_format("World") + tm_facets(as.layers = TRUE)
```

