---
title: "ruo's codes"
author: "Ruoyu Wang"
date: "2/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(shiny)
library(kableExtra)
library(shinythemes)
library(here)
library(janitor)
library(paletteer)
library(raster)

```

read in data files

```{r}
# Channel islands

channel_islands <- read_csv(here::here("data", "Animals", "channel_islands.csv")) %>% 
  dplyr::select(latitude, longitude, common_name, iconic_taxon_name) %>% 
  mutate(iconic_taxon_name = as.character(iconic_taxon_name)) %>% 
  filter(!iconic_taxon_name %in% c("Actinopterygii", "Animalia")) %>% 
  mutate(park = "Channel Islands National Park")

channel_islands_sf <- st_as_sf(channel_islands, 
                               coords = c("longitude", "latitude"), 
                               crs = 4326)


# Death Valley

death_valley <- read_csv(here::here("data", "Animals", "death_valley.csv")) %>% 
  dplyr::select(latitude, longitude, common_name, iconic_taxon_name) %>% 
  filter(!iconic_taxon_name == "Animalia") %>% 
  mutate(park = "Death Valley National Park")

death_valley_sf <- st_as_sf(death_valley,
                            coords = c("longitude", "latitude"),
                            crs = 4326)

# Joshua Tree

joshua_tree <- read_csv(here::here("data", "Animals", "joshua_tree.csv")) %>% 
  dplyr::select(latitude, longitude, common_name, iconic_taxon_name) %>% 
  filter(!iconic_taxon_name %in% c("Animalia", "Plantae")) %>% 
  mutate(park = "Joshua Tree National Park")

joshua_tree_sf <- st_as_sf(joshua_tree,
                           coords = c("longitude", "latitude"),
                           crs = 4326)
```


```{r}
# Yosemite

yosemite <- read.csv(here("data", "Animals", "yosemite.csv")) %>% 
  clean_names()

yosemite_clean <- yosemite %>% 
  dplyr::select(longitude, latitude, common_name, iconic_taxon_name) %>% 
  mutate(iconic_taxon_name = as.character(iconic_taxon_name)) %>% 
  filter(iconic_taxon_name != "Animalia") %>% 
  mutate(park = "Yosemite National Park")

yosemite_sf <- st_as_sf(yosemite_clean, coords = c("longitude", "latitude"),
                        crs = 4326)

# Sequoia

sequoia <- read.csv(here("data", "Animals", "sequoia.csv")) %>% 
  clean_names()

sequoia_clean <- sequoia %>% 
  dplyr::select(longitude, latitude, common_name, iconic_taxon_name) %>% 
  mutate(iconic_taxon_name = as.character(iconic_taxon_name)) %>% 
  mutate(park = "Sequoia National Park")

sequoia_sf <- st_as_sf(sequoia_clean, coords = c("longitude", "latitude"),
                       crs = 4326)


# join species observations data

animal <- rbind(channel_islands_sf, death_valley_sf, yosemite_sf, sequoia_sf, joshua_tree_sf)
```


# park boundaries
```{r}
nps <- read_sf(dsn = here("data", "National_Park_Service__Park_Unit_Boundaries"), 
               layer = "National_Park_Service__Park_Unit_Boundaries", crs = 4326) %>% 
  clean_names()

nps_ca <- nps %>% 
  filter(state == "CA")

nps_ca_five <- nps_ca %>% 
  filter(unit_name %in% c("Death Valley National Park", "Joshua Tree National Park", "Yosemite National Park", "Channel Islands National Park", "Sequoia National Park")) %>% 
  dplyr::select(unit_name)
```

```{r}
park_animals <- st_join(animal, nps_ca_five, left = FALSE) %>% 
  tibble::rowid_to_column("ID") %>% 
  filter(!ID == 3079)


  # For POINTS that fall within CA_counties, adds ATTRIBUTES, retains ALL pts if left=TRUE, otherwise uses inner_join
#isd_ca_co_pts <- st_join(isd_history, left = FALSE, ca_co["name"]) # join points

# plot
#plot(park_animals$geometry, pch=21, cex=0.7, col="purple")
#plot(nps_ca_five, border="gray20", col=NA, add = T)

```

```{r}
tmap_mode("view")

tm_shape(nps_ca_five)+
  tm_borders("grey40")+
  tm_shape(park_animals$geometry)+
  tm_dots(labels = "location", col = "purple", size = 0.02)
```



```{r}
# %>% 
#         addCircleMarkers(data = species(),
#                          color = ~pal_species()(common_name),
#                          opacity = 2,
#                          weight = 1,
#                          radius = 7) %>%
#         addLegend(data = species(),
#                   title = "Species",
#                   pal = pal_species(), 
#                   values = ~common_name, 
#                   opacity = 1)
```

```{r}
# # A reactive expression that returns the selected animal groups
#   
#   # animals(), first filter result data frame
#   observeEvent(input$animal_type, {  
#     
#     animals <- reactive({
#     park_animals_coords %>% 
#       filter(park %in% input$unit_name,
#              iconic_taxon_name == input$animal_type)
#   })
#   
#     
#     
#       
#     
#   # build up choices based on previous selection
# 
#     updatePickerInput(session = session, 
#                       "species", # inputId
#                       choices = c(unique(animals()$common_name))
#     )
#   })    
#  
#   output$map2 <- observeEvent(input$tab3,{
#     leafletProxy("map2", data = animals()) %>% 
#       clearMarkerClusters() %>% 
#       addMarkers(lng = ~X, lat = ~Y, label = ~common_name,
#                  clusterOptions = markerClusterOptions()) 
#   })
#   
#   # observeEvent(input$animal_type,{
#   #   leafletProxy("map2", data = animals(), session = session) %>%
#   #     clearMarkerClusters() %>%
#   #     addMarkers(lng = ~X, lat = ~Y, label = ~common_name,
#   #                clusterOptions = markerClusterOptions())
#   # 
#   # })
#   #proxy <- 
#   
#   
#   # species(), second result data frame
#   species <- reactive({
#     park_animals %>% 
#       filter(park %in% input$unit_name,
#              iconic_taxon_name %in% input$animal_type,
#              common_name %in% input$species)
#   })
#   
#   # create species color palette
#   n_species <- reactive({
#     length(input$species)
#   })
#   
#   pal_species <- reactive({
#     leaflet::colorFactor(c(rainbow(n = n_species(), s = 0.5)), species()$common_name)
#   })
  
```

